-- 1.
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", ENTRANCE_DATE AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

-- 2.
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT LENGTH(PROFESSOR_NAME) = 3; 

-- 3. 
SELECT PROFESSOR_NAME AS "교수이름" , (MONTHS_BETWEEN((SYSDATE),
(SUBSTR(PROFESSOR_SSN, 1,6),'YY-YY-MM-DD')) /12) +1 AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8 ,1) = '1'
ORDER BY "나이" ASC;